---
- name: Render HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_base_dir }}/conf/haproxy.cfg"
  notify: restart haproxy

- name: Render docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ haproxy_base_dir }}/docker-compose.yml"
  notify: restart haproxy

