---
docker_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_registry_url: ""
docker_registry_username: ""
docker_registry_password: ""
