---
- name: Configure sysctl params for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      {% for key, value in k8s_sysctl_params.items() %}
      {{ key }} = {{ value }}
      {% endfor %}
  notify: reload sysctl

- name: Apply sysctl settings
  command: sysctl --system

